### ISSUE TITLE
[BUG] Custom View ignores section

### ISSUE THREAD

**Issue by aristella** [ttscoff/doing#175]
I have created the following custom view:
```
# ~/.config/doing/config.yml
  i3:
    section: Currently
    count: 1
    order: desc
    template: "%title"
    tags_bool: NONE
    tags: done`
```

I have these entries in my doing:

```
     Tue  6:00pm ║ Fixxing ACC                                                                      [Currently ]
     Tue  6:10pm ║ Testing doing                                                                    [Currently ]
         10:37am ║ Update Ticket                                                                    [Currently ]
         10:56am ║ Acc                                                                              [Later     ]
```

When I execute **doing view i3** I'm getting:
```
❯ doing  view i3
Acc
```

Instead of the last entry in **Currently** section

Doing version: 2.1.86
Platform: Debian 12
