### ISSUE TITLE
%shortdate does not follow date_format specification

### ISSUE THREAD

**Issue by smartmic** [ttscoff/doing#72]
In my config, I want 24h time format for all outputs. However, using the %shortdate in `doing recent` token gives me %I:%M%P format, but should be %H:%M
```
  recent:
    date_format: ! '%Y-%m-%d %H:%M'
    template: ! '%shortdate > %title'
    wrap_width: 88
```
My output is
```
10:04pm > Some experiments on doing
```
instead of 
```
22:04 > Some experiments on doing
```
