### ISSUE TITLE
synonyms not working in autotag feature

### ISSUE THREAD

**Issue by AdamSLevy** [ttscoff/doing#79]
When I populate the synonym list in the `~/.doingrc` config file the program crashes with the following error:

```
$ doing now this is a test udoas
error: undefined method `each' for nil:NilClass
```

Below is my autotag part of my config file. It is at the top of the config file under the line with `---`. The rest of the config file has not been altered from the default.

```
autotag:
  whitelist:
  - microdoas
  - other
  synonyms:
  - microdoas:
    - doas
    - udoas
```

I can get autotag to work without issue if I don't try to use the synonyms. When my config file is as follows I don't get errors:

```
autotag:
  whitelist:
  - microdoas
  - other
  synonyms: {}
```

I am running the latest pre-release on a MacBook Pro running OS X Yosemite 10.10.5

Thank you
