### ISSUE TITLE
[1.0.10pre] Cannot change date format without breaking any print command.

### ISSUE THREAD

**Issue by remolueoend** [ttscoff/doing#95]
First thanks for the great work!

doing -v: `doing version 1.0.10pre`.
ruby -v: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

When changing the date format in `~/.doingrc` under `templates/default/date_format`, the command `doing now [TEXT]` adds an entry to `what_was_i_doing.md` using the new date format, but fails when trying to parse it again using the command `doing show|today|recent|etc`.

It also fails when I adjust the setting `default_date_format` to the same date format as `templates/default/date_format`.

The error message is always: `error: argument out of range`. I assume it tries to parse the day (> 12) as a month (see below).

Here's my adjusted config, the only thing I changed was swapping `%d` and `%m` in `default_date_format` and `templates/default/date_format`:

```yaml
---
current_section: Currently
default_template: "%date: %title%note"
default_date_format: "%Y-%d-%m %H:%M"
views:
  color:
    date_format: "%F %_I:%M%P"
    section: Currently
    count: 10
    wrap_width: 0
    template: "%boldblack%date %boldgreen| %boldwhite%title%default%note"
    order: desc
templates:
  default:
    date_format: "%Y-%d-%m %H:%M"
    template: "%date | %title%note"
    wrap_width: 0
  today:
    date_format: "%_I:%M%P"
    template: "%date: %title%odnote"
    wrap_width: 0
  last:
    date_format: "%_I:%M%P on %a"
    template: "%title (at %date)%odnote"
    wrap_width: 0
  recent:
    date_format: "%_I:%M%P"
    template: "%date > %title%odnote"
    wrap_width: 50
:include_notes: true
autotag:
  whitelist: []
  synonyms: {}
doing_file: "~/what_was_i_doing.md"
editor_app: 
marker_tag: flagged
marker_color: red
default_tags: []
```

The error is reproducible with a clean/non-existing `what_was_i_doing.md`.

Thanks again for your help!
