### ISSUE TITLE
Enhancement suggestion: Übersicht widget

### ISSUE THREAD

**Issue by pax** [ttscoff/doing#96]
I'd love to be able to display my doing file as an  [Übersicht](http://tracesof.net/uebersicht/) widget

PS. tried to pipe it with `ttscoff/mdless` but [failed](https://github.com/ttscoff/mdless/issues/19)

**Comment by ttscoff** [comment]
If you're using the pre-release (1.0.11pre branch) you can add a section 
under views in the doingrc:

```
views:
   uber:
     date_format: "%a %_I:%M%P"
     tags_bool: NONE
     template: <li><span class="date">%date</span> <span 
class="divider">|</span> <span
       class="title">%title</span><p class="note">%note</span></li>
     order: asc
     count: 3
     section: Currently
     tags: cancelled
     wrap_width: 0
```

Then just using `doing view uber` should give you reasonable output for 
a widget.

-Brett
